### PR TITLE
Add support for Gradle 5.x

### PR DESCRIPTION
**Pull request by hexid**
Replaced classesDir with classesDirs as required by https://docs.gradle.org/current/userguide/upgrading_version_4.html
> The classesDir property has been removed from both the JDepend task and SourceSetOutput. Use the JDepend.classesDirs and SourceSetOutput.classesDirs properties instead.

Moved tree iteration into a helper class to reduce code reuse.

@kazvictor The CLA link in the contributing guide is broken. Would it be good enough to sign https://www.clahub.com/agreements/CAAPIM/react-themer?

### CODE REVIEW

**Comment by joao-borges** [comment]
@amoghsa, I have to discuss this with you, our internal assertions don't use gradle 5 and this might affect our internal builds.

**Comment by amoghsa** [comment]
That's true, let's discuss this in office..

**Comment by joao-borges** [comment]
Hello @hexid 
Thanks for your contribution! 
I have one question. Does your changes still work when using Gradle 4.10 or this is a compatibility change?

Thanks
Joao

**Comment by hexid** [comment]
@joao-borges The only major change here is using [SourceSetOutput's getClassesDirs()](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/SourceSetOutput.html#getClassesDirs--) which was added in Gradle 4.0.

I've tested the changes with both 5.2.1 and 4.10.2

**Comment by joao-borges** [comment]
Thanks @hexid I will review and test with our internal pipelines and as soon it's ready, I will merge it.

**Review by joao-borges — APPROVED** [review]

**Pull request merged**
