### PR TITLE
Update for gradle 8.x support

### PR DESCRIPTION
**Pull request by eomielan**
## Description
The purpose of this PR is to resolve gradle deprecations up to gradle 8.x and upgrade the gradle wrapper to version 8.9.

**Deprecations resolved:**
- Replace `baseName` with `archiveBaseName` according to this [note](https://docs.gradle.org/6.7/dsl/org.gradle.api.tasks.bundling.Jar.html#org.gradle.api.tasks.bundling.Jar:baseName:~:text=String%20baseName,replaced%20by%20archiveBaseName.).
- Replace `extension` with `archiveExtension` according to this [note](https://docs.gradle.org/6.7/dsl/org.gradle.api.tasks.bundling.Jar.html#org.gradle.api.tasks.bundling.Jar:baseName:~:text=String%20extension,replaced%20by%20archiveExtension.).
- Replace `classifier` keyword with `archiveClassifier` according to this [note](https://docs.gradle.org/6.7/dsl/org.gradle.api.tasks.bundling.Jar.html#org.gradle.api.tasks.bundling.Jar:classifier:~:text=String%20classifier,replaced%20by%20archiveClassifier.).
- Replace `version` variable with `archiveVersion` according to this [note](https://docs.gradle.org/6.7/dsl/org.gradle.api.tasks.bundling.Jar.html#org.gradle.api.tasks.bundling.Jar:version:~:text=String%20version,replaced%20by%20archiveVersion.).
- Remove the `maven` plugin as this is deprecated and can be replaced by the `maven-publish` plugin which is already included according to this [note](https://docs.gradle.org/current/userguide/upgrading_version_5.html#:~:text=The%20uploadArchives%20task%20and%20the,publication%20of%20Gradle%20Module%20Metadata.).
- Replace `compile` configuration with `implementation` according to this [note](https://docs.gradle.org/current/userguide/upgrading_version_6.html#:~:text=Table%201.%20Common,%3CsourceSet%3EImplementation).
- Replace `testCompile` configuration with `testImplementation` according to this [note](https://docs.gradle.org/current/userguide/upgrading_version_6.html#:~:text=Table%201.%20Common,%3CsourceSet%3EImplementation).
- Removed the bintray plugin as this was sunset in May 2021: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Wrapper upgrade:**
- Followed [this guide](https://docs.gradle.org/8.9/userguide/gradle_wrapper.html#sec:upgrading_wrapper) for upgrading the gradle wrapper to v8.9
- Followed [this guide](https://docs.gradle.org/8.9/userguide/gradle_wrapper.html#wrapper_checksum_verification) for verifying the wrapper jar checksum.

## Verification
- Used the local built jar with the changes in an assertion functional and unit tests
- Ran `ModularAssertionBuilderTest`:

Screenshot 2024-08-06 at 4 24 29 PM

### CODE REVIEW

**Comment by jagsgill** [comment]
The change looks fine. I am wondering about the gradle output from your screenshot - it mentions some other features deprecated since Grade v5 are still in use, and those would be expected to have a high likelihood of issues with Gradle v8. How many other deprecation warnings need to be addressed in this plugin?

**Comment by eomielan** [comment]
> The change looks fine. I am wondering about the gradle output from your screenshot - it mentions some other features deprecated since Grade v5 are still in use, and those would be expected to have a high likelihood of issues with Gradle v8. How many other deprecation warnings need to be addressed in this plugin?

To summarize the recent in-person discussion, once the PR is merged, we will verify if the update is published. If it is, we will update the Gradle version in a separate task. In case that it does not get published, we will consider changing the platform for published plugins first, then update the Gradle version.

**Review by jagsgill — COMMENTED** [review]
Looks good. I think we should update the readme file (on `master`, `CAAPIM:8.x` and `CAAPIM:7.x`) to mention the repo's branching strategy which now aligns with the gradle version being used. 
Likewise for #14

**Comment by eomielan** [comment]
> Looks good. I think we should update the readme file (on `master`, `CAAPIM:8.x` and `CAAPIM:7.x`) to mention the repo's branching strategy which now aligns with the gradle version being used. Likewise for #14

Created a new PR to update the README on the master branch with the new branching strategy: #15

**Review by jagsgill — COMMENTED** [review]
The branching strategy addition is fine. I would suggest moving it under Usage, add a note that ___ was the last published artifact version. After that, users must build the plugin themselves and/or host it in their own plugin repository.

**Review by emilytzhang — COMMENTED** [review]
readme, update the license from Copyright (c) 2017 CA to broadcom standard one

**Comment by eomielan** [comment]
@jagsgill @emilytzhang Updated the README and the copyright notices.

**Review by jagsgill — APPROVED** [review]
Looks good to me. Will need to port the readme update to the master branch.

**Review by emilytzhang — APPROVED** [review]

**Pull request merged**
